# Generated by Django 4.2.7 on 2025-11-04 06:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('url', models.URLField()),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Geographic coordinates', srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'city'], name='events_even_country_0210b2_idx')],
            },
        ),
    ]
