# Generated by Django 5.2.7 on 2025-11-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name_plural': 'events'},
        ),
    ]
